package org.gitbounty.gitbountybackend.service.codebase.codebasemember;

import org.gitbounty.gitbountybackend.model.Codebase;
import org.gitbounty.gitbountybackend.model.CodebaseMember;
import org.gitbounty.gitbountybackend.model.CodebaseRole;
import org.gitbounty.gitbountybackend.model.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class CodebaseMemberServiceTest {

    @Mock
    private CodebaseMemberRepository memberRepository;

    private CodebaseMemberService memberService;

    private Codebase sampleCodebase;
    private User sampleUser;

    @BeforeEach
    void setUp() {
        // Leverages the single constructor generated by Lombok's @RequiredArgsConstructor
        memberService = new CodebaseMemberService(memberRepository);

        sampleCodebase = new Codebase();
        sampleCodebase.setId(100L);

        sampleUser = new User();
        sampleUser.setId(200L);
        sampleUser.setUsername("bounty-hunter");
    }

    @Nested
    class AddMemberTests {

        @Test
        void should_AddMember_When_UserIsNotAlreadyMember() {
            // Arrange
            when(memberRepository.existsByCodebaseIdAndUserId(100L, 200L)).thenReturn(false);

            CodebaseMember expectedMember = CodebaseMember.builder()
                .codebase(sampleCodebase)
                .user(sampleUser)
                .role(CodebaseRole.DEVELOPER)
                .build();
            when(memberRepository.save(any(CodebaseMember.class))).thenReturn(expectedMember);

            // Act
            CodebaseMember result = memberService.addMember(sampleCodebase, sampleUser, CodebaseRole.DEVELOPER);

            // Assert
            assertThat(result).isNotNull();
            assertThat(result.getRole()).isEqualTo(CodebaseRole.DEVELOPER);
            verify(memberRepository, times(1)).save(any(CodebaseMember.class));
        }

        @Test
        void should_ThrowException_When_UserIsAlreadyMember() {
            // Arrange
            when(memberRepository.existsByCodebaseIdAndUserId(100L, 200L)).thenReturn(true);

            // Act & Assert
            assertThatThrownBy(() -> memberService.addMember(sampleCodebase, sampleUser, CodebaseRole.DEVELOPER))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("User 'bounty-hunter' is already a member of this codebase.");

            verify(memberRepository, never()).save(any());
        }
    }

    @Nested
    class UpdateMemberRoleTests {

        @Test
        void should_UpdateRole_When_MembershipExists() {
            // Arrange
            CodebaseMember existingMember = CodebaseMember.builder()
                .codebase(sampleCodebase)
                .user(sampleUser)
                .role(CodebaseRole.REPORTER)
                .build();

            when(memberRepository.findByCodebaseIdAndUserId(100L, 200L)).thenReturn(Optional.of(existingMember));
            when(memberRepository.save(existingMember)).thenReturn(existingMember);

            // Act
            CodebaseMember updated = memberService.updateMemberRole(100L, 200L, CodebaseRole.MAINTAINER);

            // Assert
            assertThat(updated.getRole()).isEqualTo(CodebaseRole.MAINTAINER);
            verify(memberRepository).save(existingMember);
        }

        @Test
        void should_ThrowException_When_MembershipNotFoundOnUpdate() {
            // Arrange
            when(memberRepository.findByCodebaseIdAndUserId(100L, 200L)).thenReturn(Optional.empty());

            // Act & Assert
            assertThatThrownBy(() -> memberService.updateMemberRole(100L, 200L, CodebaseRole.MAINTAINER))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("Membership association not found.");
        }
    }

    @Nested
    class RemoveMemberTests {

        @Test
        void should_DeleteMember_When_MembershipExists() {
            // Arrange
            CodebaseMember existingMember = new CodebaseMember();
            when(memberRepository.findByCodebaseIdAndUserId(100L, 200L)).thenReturn(Optional.of(existingMember));

            // Act
            memberService.removeMember(100L, 200L);

            // Assert
            verify(memberRepository, times(1)).delete(existingMember);
        }

        @Test
        void should_ThrowException_When_MembershipNotFoundOnRemoval() {
            // Arrange
            when(memberRepository.findByCodebaseIdAndUserId(100L, 200L)).thenReturn(Optional.empty());

            // Act & Assert
            assertThatThrownBy(() -> memberService.removeMember(100L, 200L))
                .isInstanceOf(IllegalArgumentException.class);
        }
    }

    @Nested
    class GetRosterTests {

        @Test
        void should_ReturnRosterList() {
            // Arrange
            List<CodebaseMember> expectedRoster = List.of(new CodebaseMember(), new CodebaseMember());
            when(memberRepository.findByCodebaseId(100L)).thenReturn(expectedRoster);

            // Act
            List<CodebaseMember> standardRoster = memberService.getCodebaseRoster(100L);

            // Assert
            assertThat(standardRoster).hasSize(2);
            verify(memberRepository, times(1)).findByCodebaseId(100L);
        }
    }
}